### ISSUE TITLE
Composer install failed

### ISSUE THREAD

**Issue by fgiroud** [lzakrzewski/SymfonyFormGenerator#1]
Hi, when I add the package in my composer.json, then run composer install, i have the following issue : 

Problem 1
    - Installation request for lucaszz/symfony-form-generator 0.0.1 -> satisfiable by lucaszz/symfony-form-generator[0.0.1].
    - lucaszz/symfony-form-generator 0.0.1 requires phpdocumentor/reflection-common ^1.0@dev -> no matching package found.

Thanks in advance

**Comment by lzakrzewski** [comment]
Hi!

I'm very glad for your feedback! `SymfonyFormGenerator` is currently unstable and any feedback is great motivation for continue work on this library :)

I removed dependencies to unstable `phpdocumentor/reflection-common` from `composer.json`
See PR: https://github.com/Lucaszz/SymfonyFormGenerator/pull/2

Please try to add `SymfonyFormGenerator` to `composer.json` manually following: https://github.com/Lucaszz/SymfonyFormGenerator/blob/master/doc/installation.md
